require 'Items/ProceduralDistributions'
require 'Items/SuburbsDistributions'
require 'Items/Distributions'

function registerAsLoot(item, chance, allocation)
  table.insert(ProceduralDistributions.list[allocation].items, item);
  table.insert(ProceduralDistributions.list[allocation].items, chance);
end

local iReg = "Books";

iReg = "Books.Nineteen_Eighty-Four"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Ego_and_Its_Own"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Communist_Manifesto"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Frankenstein"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.A_Tale_of_Two_Cities"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Hobbit"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.And_Then_There_Were_None"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.You_Can_Heal_Your_Life"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Charlotte's_Web"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Tale_of_Peter_Rabbit"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.To_Kill_a_Mockingbird"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Adventures_of_Sherlock_Holmes"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Prophet"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Exorcist"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Neverending_Story"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Matilda"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.A_Light_in_the_Attic"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Giving_Tree"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Dune"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Nancy_Drew"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Chronicles_of_Narnia"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Herbert_West--Reanimator"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Conan_the_Defiant"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.On_Stranger_Tides"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Pride_and_Prejudice"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Shining"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.It"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Lord_of_the_Flies"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Animal_Farm"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Catch-22"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.To_the_Lighthouse"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Housekeeping"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Under_the_Net"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.An_American_Tragedy"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.A_Handful_of_Dust"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.At_Swim-Two-Birds"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Herzog"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Death_Comes_for_the_Archbishop"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Bridge_of_San_Luis_Rey"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Power_and_the_Glory"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Big_Sleep"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Death_of_the_Heart"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Loving"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Possession"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Slaughterhouse-Five"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Catcher_in_the_Rye"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Great_Gatsby"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.American_Psycho"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.A_Clockwork_Orange"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Fahrenheit_451"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Odyssey"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Iliad"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Trial"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Madame_Bovary"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Journey_to_the_End_of_the_Night"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.A_Doll's_House"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Invisible_Man"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Leaves_of_Grass"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Man_Without_Qualities"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Hunger"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Book_of_Disquiet"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Dead_Souls"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Decameron"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Castle"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Complete_Essays"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Demons"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Père_Goriot"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Gargantua_and_Pantagruel"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Metamorphosis"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Stranger"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Adventures_of_Huckleberry_Finn"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Ginger_Man"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Adventures_of_Pinocchio"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.James_and_the_Giant_Peach"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Lust_for_Life"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Watership_Down"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.East_of_Eden"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Canterbury_Tales"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Moby-Dick"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Flowers_for_Algernon"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Mansfield_Park"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.One_Hundred_Years_of_Solitude"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Treasure_Island"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.The_Three_Musketeers"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Old_Man_and_the_Sea"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Scarlet_Letter"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Of_Mice_and_Men"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Macbeth"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Alice's_Adventures_in_Wonderland"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Through_the_Looking-Glass"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Persuasion"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Secret_Garden"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Great_Expectations"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");

iReg = "Books.Dracula"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Count_of_Monte_Cristo"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Hamlet"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Romeo_and_Juliet"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Diary_of_a_Young_Girl"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.Factotum"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");


iReg = "Books.The_Art_of_War"
registerAsLoot(iReg, 0.2, "CrateBooks");
registerAsLoot(iReg, 0.1, "DaycareDesk");
registerAsLoot(iReg, 0.1, "DaycareShelves");
registerAsLoot(iReg, 0.1, "KitchenBook");
registerAsLoot(iReg, 0.2, "LibraryBooks");
registerAsLoot(iReg, 0.1, "LibraryCounter");
registerAsLoot(iReg, 0.1, "LivingRoomShelf");
registerAsLoot(iReg, 0.1, "LivingRoomShelfNoTapes");
registerAsLoot(iReg, 0.1, "Locker");
registerAsLoot(iReg, 0.1, "OfficeCounter");
registerAsLoot(iReg, 0.1, "PostOfficeBooks");
registerAsLoot(iReg, 0.1, "SchoolLockers");
registerAsLoot(iReg, 0.1, "ShelfGeneric");
registerAsLoot(iReg, 0.1, "ToolStoreBooks");
registerAsLoot(iReg, 0.2, "BookstoreBooks");
registerAsLoot(iReg, 0.1, "CampingStoreBooks");
registerAsLoot(iReg, 0.1, "ClassroomDesk");
registerAsLoot(iReg, 0.1, "ClassroomMisc");
registerAsLoot(iReg, 0.1, "ClassroomShelves");
